### ISSUE TITLE
crashes while deleting a 'receive' connected between ‘fl.store’ and ‘fl.recall’ for sync

### ISSUE THREAD

**Issue by opasquetdotfr** [AlexHarker/FrameLib#104]
Hello !

-- It crashes when I force Max to sync ‘fl.store’ with ‘fl.recall’ using a send and receive. It is unfortunately normally not possible. But i still do it. It is crashing when trying to delete the 'receive' hooked to ‘fl.recall’.
-- It crashes when deleting a sync connection between a ‘fl.store’ located into a subpatcher and a ‘fl.recall’ a patcher higher. 

<pre><code>
----------begin_max5_patcher----------
1022.3ocyXssbaBCD8Y3qfgmS7f.iMtSeo82HSGFYP1VsxRLRhDm1I8au5BW
DXvklllo7.jrqzd4rWzZ8Ceuv8rKHQXvGBdHvy6G9ddFRZBdM+uW3Y3kBBTX
VVHE8Da+WCuyxRhtHMjqZoTAkEmvzi4bTgzJ3rrzUIlmH6Sxt6B.YYqhTe.l
OwwqhB9RiHn0mwTBRZTXTOQVsrkJngJtznckEcOHp0DrqS9bExp+vvNQarND
uw+ZbPuvCXB5QDWfYTGo6EBqpbH64rEMp7UlQPY20QBSsjR5HwQOhGKVkb4J
LRp.nZtwFCurYcXuXXkHNsFa1ik3K9sljIRPgmQhJXgcy5.VK6dTOcmAeiS0
e1rNR+YcVTONqhzGIrhugJcvYE5UgnXZEGIPTIT1X6crKQGf0DY9AFUJve2X
A.UzaJ9GZrvIYp8Ai4+INFR5bfibbIipMhAQBM4V08P.v3T528NiYETX0DaV
kdnfkYXJTNYsXOjqCT6IFMD2xTxXjgr51GAcP1vtBSoiPQIqZdlb7wS2Xu6Y
JlmukrMbD40TK2bUNgLW.ebHZKgDRS45PweARwmgRjDaCAwQcLQTnxQOIJ3L
BYf+Z473DbJU43EnmvkxSFE4lLnVNtpMIJrKJWhOhDxgzjvihgTDxmsftCo5
8M0v4Rz4JhxKFt.U0AVHEmXOIZVXahlK.z2yysl1s22.52pG3v9fGHqDRFG8
y.HAcI+Dj+MU6FmUNQ+wTSsIHJZlFhW2TLdHiqaLNt4XpqILU+wVtu3629G2
8JQGq3+M975cq1od1tai4YKHSejftORPRT664A.vr.Pzz.vNW6ofc9rp41fD
Gy5oknKNccG.G8cZHX5b4OFOUyeZbRvp4EsndSbIXnapJYjXZWe2G5Le85lz
r7cOfHT2EnL21wKGJkb79Zo0bcOw6OpxTcLwdHYT4zTEt98Fm4sMIZIiUzFR
FOWwGu+96Cj7mCjrfRjJHiBjmvh10c8AIAelQJuwvH6.qM0WphNvFmmXyLI.
CusyMLBXxgQhtdXjstFX2wjpJ6WAzLyDWpNMJuR0hepVMS44ayrdd1lUatxy
iit8XXwKcLrM2ZJr+mSLRaff+sIFY+GlX.rkDIpQE+GlXr9MNwXFumGbptTM
+r3.FQJyEOSKtgquNJ0FziG55oa0mDmbkqWvH1I7UnllYT2Kve8OfI48AfDu
J.RkFLA.k9V.PKt1IN7MsHY14zlCGRbe.qW9ugcw0Hf2mTf+3NDIQuGGcjks
P22nmgigYQiwie0fIWM1k9tB5m6ZlYtTmjE.lA1WrhVfdh6ms6UqmjEnGM7N
xgr.4na4PqiQ2twna135a0X9azX7sYXFTctawv+E+ek0OJUF
-----------end_max5_patcher-----------
</code></pre>

**Comment by AlexHarker** [comment]
I've pushed a fix to this for main now. I'm currently working on automated builds so if you want to test the fix I should have something in the next few days.

Thanks for the fine @opasquetdotfr !
