### ISSUE TITLE
xcodeproj for Xcode 10.1

### ISSUE THREAD

**Issue by nagra00** [AlexHarker/FrameLib#112]
Could you make a xcodeproj file compatible with Xcode 10.1 available?
I do need a MAX build without AVX but can't compile.

**Comment by AlexHarker** [comment]
Sorry for the delay replying. I'm not sure how easy this would be to do, but I could make a non AVX build available, as I have a branch for this and can build on CI - any good?

**Comment by nagra00** [comment]
Sounds good !

**Comment by AlexHarker** [comment]
OK - try the max package for here and let me know if it works:

https://github.com/AlexHarker/FrameLib/releases/tag/framelib-latest-rosetta-build-2023-05-29

**Comment by nagra00** [comment]
Have tried the tutorials and it works. Thank you !

**Comment by AlexHarker** [comment]
Great - glad to hear that!
