### ISSUE TITLE
shift + drag functionality

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#39]
shift + drag works between a framelib object and an out such as fl.sink~ but not between FrameLib objects.

Would it be possible to make it work for all?

**Comment by AlexHarker** [comment]
I know this is an old issue but I am aiming to wrap things up here or not. I will give this a think, but I'm not sure it is possible without removing the restrictions on connections of FrameLib objects. Max calls to see if the connection will be accepted *before* it disconnects the previous connection, so FrameLib interprets that as a double-connection (disallowed). It's possible there is a workaround, but I'll have to see. I suspect I cannot get accurate info to let me know this is happening.

**Comment by AlexHarker** [comment]
Work is on https://github.com/AlexHarker/FrameLib/tree/shift-drag. Once tested more thoroughly I will merge into develop.

**Comment by AlexHarker** [comment]
Addressed in 5819d4db2c391edf34b064c3b5b1b3b7d6b9a556.
