### ISSUE TITLE
Crash while trying to create a connection between inlet and fl.recall~ sync in

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#44]
I receive a crash when attempting to create a connection between an `inlet` object and the sync input of `fl.recall~`

The problem can be recreated by attaching an inlet object to the right inlet of any fl.recall~ object

[patching_crash.txt](https://github.com/AlexHarker/FrameLib/files/3790119/patching_crash.txt)

**Comment by AlexHarker** [comment]
The testing for which inlets of an object are valid were incorrect.

I have fixed this in 630a7230f460d1bb50cf1fa55a80fc26a9a8d716.

The change has been merged onto other branches.
