### ISSUE TITLE
crash in very basic network

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#45]
I am on the latest alpha build of dynamic contexts which is posted in the discourse. The crash log and patch to test is attached. Press the bang, watch it crash. Do the same but WITHOUT fl.tomax~ connected to the network.

[crash.txt](https://github.com/AlexHarker/FrameLib/files/3806638/crash.txt)

<pre><code>
----------begin_max5_patcher----------
667.3ocwW9sbiBBEF+ZySACW6lpnlX1Wkc1oCQIVZUHCfcyNcZd1W7fl+z0t
ZLoYuHj.h7c9c.9f71LO7Z4NlFi9N5GHOu2l44AM0zfWacObEcWVIUCcCuoT
Jpqv9tGY+or1TxLvCIsstkZxdhKJdTwxLtAOhrXdfOJJNn4qDnjPlGf9Y663
FFyu2xbu.F6ivqohB7gtrQppnv3snsEdNDSx0O+sD7AwUzJlgodjInqKggK3
X3xEcQaXSauOaVSg+HoWv9kUrNoLrcl1jxbiz1w88mWBGNuDj.4kzQjWN7nS
nmfuCDRK1iJYhBySWLlDxpSvb4TwLdYubRtobZW9rcO5gZA2nQZakRlF8fNi
VxPYxZg4hoON8j09jffoRex8fdFMeOJuNu9kOjClJ1o.ugKRlJ1w2Ar4hMxK
A6ngvlrHzg8Hs5fO8hezMC+00FiTLw4wvEDfj3txOmmyssOkEx+SW5rRd1K6
mJ9qbqlWM7zolWHnk8m.BtCF0z5btzn3EEL0TwkPfuRmpScT5MCzJlVSKX8L
cxnpKFuP2YrIticmpmDI5q1SZc8lM1oOjMdPwAAW7EtZWutB1tlNhUs1K1Yu
bk++X2aX7W8h2Nnc9vP4bJeyTg2MIGFEeKneX3g2BWxEe7F0PD1z94YDsrVk
0E.s2hCcLFyYZCWPMbqk8w9j35Su47wpSyQJCJz4AiTkyTfI80obxHTt4.+q
mwkiQolvI7djM+.3GRmj6fzK6W5vqR5FC9gkN5VLSNlsEMGrd8JELBk5.+pT
hLlItv+defyhgtc6qLkts2fHV60mkvzZpOTkKbUgKUgUrW4c8G9yyXpxZZZr
Nl0JHvv6V3b3vUR6BDQMucMhEOqjf0svdkM8VpiDvge16y9Czcixy.
-----------end_max5_patcher-----------
</code></pre>

**Comment by AlexHarker** [comment]
This crash is now fixed in 19935119be9fa1f4d5e46ce3b56acb28de7e73eb and 8ff9f996b2442b981e6a7af1b6a506483f97d736
