### ISSUE TITLE
fl.samplerate~ needs a parameter inlet

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#53]
fl.samplerate~ should be able to have its conversion mode set in real-time, not just when the object is made.

**Comment by AlexHarker** [comment]
This was a design decision - can you give a use case? It would be a single line addition to make it happen, but I think I imagined that you would rarely need this to be dynamic - perhaps I was wrong.

**Comment by jamesb93** [comment]
The dynamism to be able to change units without recompiling the network alone is a decent reason. Perhaps I am not seeing the value in preventing the user from adjusting the conversion, does it add some kind of overhead that is not obvious?

**Comment by AlexHarker** [comment]
I'm asking for a specific use case - obviously adding a parameter input would allow the user to change the conversion, but what I'm asking is can you outline a case where you'd need that. It can be specific (but ideally not super-esoteric). When I made the object my reasoning was that in most sample rate conversion tasks you know ahead of time what conversion you need and you don't need to change it - perhaps I am wrong, but if so I only need one simple real world example to convince me.

**Comment by AlexHarker** [comment]
Added for consistency with fl.convert~ (as raised off list by James)

**Comment by jamesb93** [comment]
:)
