### ISSUE TITLE
Naming of inlets on fl.lookup~ is confusing

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#57]
The wording of the inputs for fl.lookup~ could be more concise. As it stands they are a bit confusing to me but it might just be lack of familiarity with lookup terminology.

Inlet 1: "Values to look up"
Inlet 2: "Frame for table"

I think it could be more explicit such as:

Inlet 1: "Indices of Values to look up"
Inlet2 : "Values to be looked up"

**Comment by AlexHarker** [comment]
Thanks - this object hasn't been reviewed yet, so I would likely change this, anyway. I may not use this exact wording, but I'll try to think of something better.

**Comment by AlexHarker** [comment]
OK - I went with Input and Table Input as the new style is quite brief - please review on object-review (along with the info message) and see if it is less confusing.

**Comment by jamesb93** [comment]
That makes more sense. They are both inputs, but making it explicit that one is the Table Input makes it a bit clearer.
