### ISSUE TITLE
notification that offline process has been completed

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#58]
I realise this is still conceptual and not settled yet but will be there a way to be notified when an offline process has been completed (writing to a buffer with FrameLib networks)? Some imagined interfaces are that fl.sink~ might output a single trigger frame when the job is done.

Or have I missed something here that simply structuring your patch with `t b b` will be enough to guarantee that the FrameLib process will complete before moving on to the next thing?

**Comment by AlexHarker** [comment]
Yes - you can just use trigger and after you've told it to process the next message will only be sent when it is done.
