### ISSUE TITLE
Inccorect values from fl.convolution and fl.correlation

### ISSUE THREAD

**Issue by Pezz89** [AlexHarker/FrameLib#60]
The convolution and correlation values produced by the FrameLib objects are currently incorrect, due to an issue with operations on complex numbers in the frequency domain (SpectralFunctions.hpp). The following patch demonstrates the issue by comparing outputs from the objects to the expected outputs as produced by the equivelant Numpy functions in Python (these values have also been verified to be the same in Matlab)
A pull request with a suggested fix will be submitted shortly...
`
----------begin_max5_patcher----------

1805.3oc2Z0raaiCD9bJPeGHTuzB3nv+DkTv1C6dYeAJVfEwEEJxzNpqLkgD
UZRK18YeGRJ453X6n3JIGDjXKSxghy7MCI+FJ8i29ly7tt3NYkG5RzUnyN6G
PMmYqyTyYsUbl2xj6RySprB5kVrboTo8lzznVdm11vuc94nOUWpPEJTR8rrB
j9FoBspTB8rU57LkLsnVY6BssViLv8LQmUn9xdDIQmdSlZwWJkoZmFGK7Clf
3wQ93IHR.1bgw8wnO21IU8xLUtTa0bxF0VTqaqF2Vc1LqYTb8WOOxyV2+912
XtBWlbZgm8Y6jP628ooGd7l9x5bcVUd1LYo2AT8.g0gwvByEZHw59Xrmq1uF
dpx9tzJW7OG0xjkRsr7KRUx04xGXrtag99URm934MA97ywtRpgAGrLWyNrEi
2T81.uBFK7J50AdQNd755ZstPcHnhyYlQmGEZgJd62OOfhbbvx0IpEd6zlo+
BwHvpCIKjOd4DR7g.BVzl.ga8AJcu.A8I.hGGBrS6jiOdCUI+FbKdrc98b+b
o5v1pcFAmSsQdgGmsR6Z39F1KKp+s27hjY1HoCsh.1th.EyLK+GD8DVL445c
2ejb.4jZwhP6T5Q0hwCvjWrOh3in9HlOh6iB7QBeTnOJxGE6evXcLaCbfvGq
I1CPf97becAH4+cH6k5H2IbqqKn8seeOla7KJetfrwr8wymKNQ97F6kDhM16
n4y4C.m++JIuVVgVHUxxDsbF5aY5aPqtWeCjDPZwL4kSUSUYKWUTpQf9u5dT
RERsxT6cnOB+xGnfnVHeOA+Az6PokR31fRJKStGULGcq69OurXog2E5bHTBO
UU55ZZQYoLG5v6uaBB9eILfebp27577odeXpB5cUqjpTPNkQ12Wd0kk9FNhW
bA8ySPkWstzke9C6NSkvml9p.SstStc+YBl0GIqvYudbZOvabaQ9s61sA2vG
TwknOciDA3zpZMJqxjTIxzBZVVELxv.a7TIkH2cs1jhsQKLxkofNU4OU8Nzu
mCzbA+e1sx76mprJWUZ1p6Ae+BURNpwdmOW2pdfT+rfUW2SzQ7SGcPHT257t
nCFoWhNFBd2zn.HkBLj7j.R7lCZd.jZFPPAQEnXDF9K17SnBnZSqVo.ogd87
yyuAeBCb4x3tvDC8h+Lxv.c9FTv2.G9Fbw2.PvVfPUPNJ.rY1KDcN18I1Uio
EiDVQccxzcyM54imBwFvICtiiBbRF9SIf+p5PBNU7McnnHNbLoaRhGzyDIxc
D.rWVGIx.bTAo4Yo+SGbuAL6ENoucutsJ2iASFjPZ6IIqKyVrPV1ESOzNyKN
Xbhro7AwngPvU+G5hboZAvLifOXFjgVaUPvNdmQiS1SzfStk2rVFKXbM7gIs
w04x.VOzmF.fQgR.aXfz0ExYK.V0cAQDMmNrXjPjvAfKUKGIh8vDHFxSvGvW
CLFA5Rl5LUPDFJWXSyvh9HJyPbxHE01Zr4KNzPD4X3R41eLf33RwFItThg3v
YfHHBB3oCz3w.LBnH.hFLz.gFDz.fF7y.eFzy.dFrCftilUeCzQGKZnT5HQC
8Uxy1iDdRogRaRJdrngxGdZnT6g.8hgEJgbBYgZe18iKITB8k.IznXikOVbP
IrSOGTvhsqCxsmf+XQEifegvAcrMb1.QA0cTm+5LPadzFTd3H8nb1FObRY4q
r8a+kUoMMrEJUUTWl1NLMjIlf1PwmIqzYJ6qv0FRE3DZ+9iNOdl.smd737GJ
UQogvhY6gwSE.gH6PCH8fFv5pBzOXNizkwizaiWPmFu1Hu9X.6jGk0eVHOtS
dvnGFCsLa1phLktp8s.vxcPHraqvYr0k5Gcj2IcTbXczsFGIN18RZRVWpezw
NEX1iyDh5DlfGx49cREnC35ezvNg5w8FpSEcxjC6uALnSt43gDjC5rMOTQZz
NM6ZamyoPE1Bq1ZMHWJVBrKGqH95RCkqqaae0eqJQ6z1Wz9a6KRm19hDMfQF
cTEBN3tStHiPp6LKCIqKMTLG6T371qvuSklF6dOWiwqKcRUZR3db1zwSEDcv
YSad+fEAqKMTQnchkNaHmizIMX6zY1IrQnLWbVz5RCU3VmRnr0z5iAraY2r6
rMZRgNY0pakkUMcwMVdKS9ZgEVhl3JmobkcIt6UJuMqsKAtpRJSuISKS00kV
Uz6NA2qo2E.HqpyZCNLVqYnqz2m+nz2UIKkabPF+Qds771GPAXfySpy0agKI
ooRkNsH2oilSEmQBE7Pvr8EA7XL07qXSUDHDXyrLlzB4kvsvpP1Auc.sOzf0
wGOzMskl92x77hucD5ZDMfXU0vHRDw7CbPb.OnQSactyK.Er4gIbExbx5AwX
bTOaJ0KuVV9mE4yNBCwfuXgw.Bhoj.qMQvjXwuJn2DpZOjKipVsJwMOvdXXu
8MfH+O3yt6gG

-----------end_max5_patcher-----------
`

**Comment by Pezz89** [comment]
Pull request created with potential fix for this issue #61

**Comment by AlexHarker** [comment]
Thanks for looking at this - this code actually lives primarily here: https://github.com/AlexHarker/HISSTools_Library

If you look there you'll see it's been totally refactored (and it looks like I solved this issue with a store method), and that has been pulled into the dev branches here, but isn't on master...

**Comment by AlexHarker** [comment]
See https://github.com/AlexHarker/HISSTools_Library/blob/8f588f9c16e5170ef39dd066e93b1ca2f9433b6a/SpectralFunctions.hpp#L274

**Comment by AlexHarker** [comment]
And this is the most recent branch - https://github.com/AlexHarker/FrameLib/tree/time-smoothing-decisions

Sorry that this has tripped you up - I can see that I aliased the pointers and then didn't deal with that properly - it was revealed during my object review in which my testing was a lot more rigorous, but I've still a few objects to go - an update is due very soon!

**Comment by Pezz89** [comment]
Ah yes sadly the thought that master branch might be significantly behind the dev branches only crossed my mind after I'd raised this issue... 
The most up to date branch doesn't appear to be building correctly in Visual Studio, although I presume this is because it's being primarily developed in Xcode. If it's a quick fix then do you have any suggestions for fixing this build error to do with the framelib_objects.lib file not being generated? If this is a pain then I'll just carry on tracking master with my hacky fix until the new release.
![Capture](https://user-images.githubusercontent.com/10585430/87544597-a561bd80-c69e-11ea-94ec-4a5e5971ec54.PNG)

**Comment by AlexHarker** [comment]
Yes - objects have been deleted and renamed, so the VS projects need updating/deleting and a couple added. I can look at this but possibly not till next week. I think I have a VS project generator (as a max patch of all things) to make this easier, but I think it's a couple of steps to get it all right.

**Comment by AlexHarker** [comment]
OK - turns out it wasn't too bad - that branch should now build for windows.

**Comment by Pezz89** [comment]
It does all appear to build now (aside from `Error	C1083	Cannot open source file: '..\..\..\FrameLib_Max_Objects\Time_Smoothing\fl.ewmsd~.cpp': No such file or directory	fl.ewmsd~`). Unfortunately when I open the example patch showing the issue with fl.convolution and fl.correlation, all of Max locks up and doesn't respond, similar to how it locked up when I was accidentally mixing release and debug builds, although I'm sure I'm not doing that this time).
