### ISSUE TITLE
info for fl.kernelsmooth~ 'seems' incorrect

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#64]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/13281862/92726016-e1469580-f364-11ea-94bd-6ca50a88b09c.png">

I feel like this is pulled from chop or subframe. Anyway, just putting it here as a reminder so it doesn't slip through the cracks.

**Comment by AlexHarker** [comment]
I'm tracking info strings elsewhere - many of them are not up to date - but thanks for spotting it.

**Comment by AlexHarker** [comment]
Now fixed on object-review
