### ISSUE TITLE
Getting "system security policy" on 10.14.6

### ISSUE THREAD

**Issue by rconstanzo** [AlexHarker/FrameLib#67]
@jamesb93 sent me over a build of the most recent changes, and when I fired up Max I was greeted with:

`framelib_max: cannot be loaded due to system security policy`

This points me to a [c74 article](https://cycling74.com/articles/using-unsigned-max-externals-on-mac-os-10-15-catalina) that talks about Catalina and sandboxing.

The thing is, I'm not on Catalina. I'm on Mojave (10.14.6):
![Screenshot 2020-09-10 at 7 05 18 pm](https://user-images.githubusercontent.com/2747015/92778464-1bca2580-f399-11ea-90d4-b34e3af31861.png)

**Comment by AlexHarker** [comment]
This seems annoying, but given that this isn't a build I made and James was getting similar issues on build I'm not really too worried at this point. If you have been able to load old versions on your current system, then I see no reason that would change with a build here.

**Comment by rconstanzo** [comment]
@jamesb93 probably ticked the "fuck it on 10.14" box in xcode.

Sadly, the last working build I have is pre-M4L fix. (#52 )

**Comment by jamesb93** [comment]
This is because I sent a compressed zip containing a dead single object build from a long time ago. My bad... 👎

**Comment by rconstanzo** [comment]
Don't know if it's related to the build thing (which is now working), but I'm still getting crashes as per #52 , which I posted on a comment on that issue. Don't know if that still shows up since its a "closed" issue.

**Comment by AlexHarker** [comment]
I'm going to send a build to @rconstanzo today - can you close this issue if the issues do not appear with that build, or report otherwise.

**Comment by rconstanzo** [comment]
Not getting this error since v.1.0-beta.
