### ISSUE TITLE
fl.window~ /window parameter has inconsistent casing between kebab and snake

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#68]
For illustrative purposes:
```
nutall_continuous
flat-top
blackman-harris
```
Although not a huge deal I think the casing of these is not right.

it should be:
```
flat_top
blackman-harris
```

I believe flat top is two separated words in the literature whereas blackman-harris is hyphenated anyway. This makes blackman-harris the only hyphenated one which is a little stylistically weird to code around but more correct in terms of the word itself.

**Comment by AlexHarker** [comment]
I do appreciate you looking at this, but this object is mid review and I'm aware of this issue and I need to make a decision on this and various other things in the window object - the difference is partly there so I don't forget.

**Comment by jamesb93** [comment]
Yes sorry. I am coming across things as I update old help files and Max Documentation. Take these issues as friendly reminders that I've seen things which may or may not be of concern to you.
