### ISSUE TITLE
Inputs out of bounds for fl.random~

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#69]
creating fl.random~ like so:

`fl.random~ [1] 0 [2] 3 [3] 0`

tells me that input [3] is out of bounds. I believe input [3] should refer to the units parameter.

This wasn't the case prior to merging the tip of object-review. Please ignore if this interface has become under review.

**Comment by AlexHarker** [comment]
You seem to be confusing inputs and arguments. fl.random~ has two inputs only. The third **argument** is the units argument.

**Comment by AlexHarker** [comment]
Also - if you are trying to set enums I don't advise using numbers - I'm vaguely considering removing this to make enums easier to change in the future. I'm aware that it's hard to change them any other way on the fly at the moment, though... However, here you are instantiating an object.

**Comment by AlexHarker** [comment]
@jamesb93 - can you review?

**Comment by jamesb93** [comment]
What would you like me to review? I came across this in the tutorials that describe all the ways to instantiate objects which I've now changed.

**Comment by AlexHarker** [comment]
The issue - if this is a user error please close.
