### ISSUE TITLE
tukey and kaiser windows dont produce correct window (for fl.makewindow~ and fl.window~)

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#71]
Again, I apologise if this will be changed in review but perhaps you are not aware. I am not getting what looks like these windows from either object when setting them to tukey and kaiser. Have I done something wrong?

<pre><code>
----------begin_max5_patcher----------
2127.3oc4Zs0bihiE9YmeETtlGSmQRbeealplZ+CrurUWS4RFD1JAjn.QR5t
qY9su5BWDXvlDmjt6YewFNRfNmuyUINe6lMa2yelTu04e47YmMa91Ma1nIoH
ro89MaKvOmjiq0SaaBunfvDau0Llf7rPS++bj3vaDkMBGdlSV9cE3GHOQYo7
m9amDdSdpydhSSMI0QvcLC3vEGIUNYU3BR8ccuxbJiHe.l9850RjlpWE996+
DBzMyRrH4HkcXWEIQXDBT.5N+acB.92At0A56p9KPdiye19PrlBJKmHzhCbf
nj46nBTD+qatQ8ysqDWXjmjL2IvhDHxpjPF94+1oDKEz5smJQvnNhFlP7kRh
Qb1tsmumQXgQ.k344ZDVjm5Oj6KSXguBgsnIWPqyoojp4DG+AEjR0JHU6HL7
9bsPAVTTu0VbqoeUOfGHNniDQHkFIiXd.srCsD14LGPpI4G4aPFn9Q.uPyAz
ap4ffqLFlC1becVAsxnmFOBPeT1.KKgkjp847jGlUHQWiP5Fo+Kz+iRH2qYk
Aq7GojmdjVS2SyohuXuV7rLo8okkIvh6TnAIMsBenNohmma6GjjSSdPbrh2b
3nMciGywSe.y.Od5.6OTvSG4ismWobQsXSaUA7ph5.MgXcgl+.fkzFf40FcR
SwdRpMgND2nTZ0Ja1lQkxLoplxYVydyVbYoE4MVOhRUdOW+hhtsmDkwsADIo
JhRiZdd2dp3JobKjBcSkFU19bf21gWiDnqXMzd6JsQUKKoMeXpbZk3DyCqrx
5Fd.IiB0Ajb80V0dggZGYHZ.IUJUiwiERJUXkDFkUVQpkohwhoXRJICKiPuK
iyDcwQUu04FOqkEmcPkPn4+eqhhy6kfCUzTNSwDiVVE4tkSZlzlA1VXzyfgK
m4gkVjRbYgAqkBYS8dbk12yjGA0MnfyyGOT+ykSxDsCWRYrInnfWt7fUzCGO
yytmKGr3bua8H06ZXlQ2IMJD6pwONFsE3771Hoie8OiYzBrfHnFU.BzO3IQF
fiG4wYFIUZjmHqGKUXBxXaLHmNsryHZauVNkdfTKFSSHifMlRs3KFP2hTSWX
ycBRQYtTJFOgQEcZ6wZGNdD8yk6Yb9mbNNU54UKqLvdb63dd1CrbruESE4pi
+EaREoKvDY6xtT5nkRIsoKsTaTjWIljSejb2nZxLYrvU8dwKLE63H1xoupRZ
XbfNFUr52nvIxocY4idkyT3G7rn9spRG3XwD3egPbKkZRqMfdZl0CNKKuRUC
xZDkWa5NrPTQ22HHCWUaoWrTLJTOugvyrG1dba.JmyNbAMzn4WzV.rauK7zY
TejWMD59OdVFQcXGamL6NkvRusFFUz6jCGlSuIq8kuA1wi2f4Xm61sMl0vRz
VDW1H13k1ZW3ZbVAKaDGs80a74BLudXrIwGX1EaklefIh+8M0BZFMYfY9ffb
BKsjSk0QrlHFl8f.C851084Q6vq.sQQQlWu2+jPa4XxZepwqz5FB8zwnM.dG
hrLf6cM.tIUGL5eVl2mFcbwPIV11gnKA0tWCT6GYsV+LA0pJuvGHmORhyu.W
pzL+qqzLXjoXEfF+L6m570lg93pMSf2e1Byji+Y2+7EDl0TYVf2kpLC5d0kl
sP4YRDam53Zq2M0B2yZVXYx5GI6OvYI7bytuUmQRrePT.JzyGDGAbiUmXRbL
BZQUQBFEgjaPN1CBCC7BGcheupRD8gV0Ht.3sRWK24gh1EcJL7AWE4IlSyWE
4ppgr+EBW7ERj.PqASFsRtuQoEiZKup+kaV9n5elLT6HCnYKDEslBQAu+EhZ
TzKEoZx1cVXqHtAwl.Rc+dsQv6xkYueZMqwRIO+gFMuMw4YBlCuxf4t1wx8+
QIV94.k9x2HmAV.WGrDCrfkX3OCvR611VDRhuxCjIzFRB7+oKqOZMY8glOAR
aVeSw3mKqevOlI8iC.gQdtP2PjumNoO7zj9gipL.c0I8Me1n++HmO56RNedV
lNiuDMvUpqJ4OQzWH0BbVsnpIQ7ySt+055tF+VSZLSTIS7Znq2YpV+i2uM7p
Ow01CVCMuz8l4ZE9c005R9UPzKxwZEdUGwLlRadDWTnf.4kRgDyNHsDzWiKI
ekKMdT2z7.4KpKpkvl5+GvzZiK39bbxCEXl80e5HtphVqKKuQn9LT6j9oBJq
g2zQUQTttF6Ir3SBdYqGsvvCe39yCeJQsww7eCIsEiZ74czq4MUIc9Kske3L
1fMkTKQhdefOOTyuZhqJNyKkIBVKS.NYhEztin0TfHTclfHW8oeDG2ey6Diq
Nylu+vm5LNVGW3eI7CF.zXVr4z2h86u68h2g+PfffeH3hUxDwWRKhz8AX6Ym
BrNGUygoZTtnv32akKZsnJ78DU8VIWrrpskngxaVqhY2jn+ZNgcPbT2weyz4
X9WSii401yRsGI7hcNF5Mqywtutg1KEGXbIGoZzqE5EK2WWGS1KDptipu.CI
tdjjWpt+t6qOSyxNzhN8MQZ3E6Mx6qwUGZTGBUc248MROt09wmoguF5IM61r
U+PiSpaP4ol5sX8EBhtjSVzf88I5y0tR9qYgbeCVnNt8rqjhafW6B4tFQx+s
PjPqTjFlyPKL99uxSP7IoTb0EV4g.ceGzt6NkWO0zdReJpXyI8m3jdS7z9Rb
4dRbZ+Hp6EQSqYMwcpOHgIl7uK2QT2NN657uw.INIQ5pO5Lbba+RLf6B78hA
H8WtQQB1dPM2LzNjp.ZpPES5RLSGj2gT15yIL3+kjmye5EyhQHenlCCifQPc
Re+XeO+wMLtc+Q9YcGR5GC.QuUBPSwdR0+lmm9hYeEXBBTrsu5vwzRBD.iCd
8HrwJbgVS8l+5l+mJeyfy
-----------end_max5_patcher-----------
</code></pre>

**Comment by jamesb93** [comment]
Ah I see, you have to pass the /parameters parameter so that the parameters inside...

```cpp
        inline double kaiser(uint32_t i, uint32_t N,  const params& p)
        {
            double x = 2.0 * normalise(i, N) - 1.0;
            return izero((1.0 - x * x) * p.a0 * p.a0) * p.a1;
        }
        
        inline double tukey(uint32_t i, uint32_t N, const params& p)
        {
            // FIX - look at normalisation here...
            return 0.5 - 0.5 * cos(trapezoid(i, N, p) * pi());
        }
```

....get unpicked

**Comment by jamesb93** [comment]
In addition to this I don't think it's necessary that the console tells you if a mode doesn't take parameters after setting them for another window type. If you switch the window type (imagine you have a big patch using lots of window modes) it's going to be spitting red over a potentially well considered use case.

**Comment by AlexHarker** [comment]
These items are in progress and there are already some changes in my local working copy from a week or so ago that address  default parameters for windows with parameters. Things on this object may change further - the error about parameters when none are needed will likely disappear, but there will still need to be errors when too many parameters are provided. So - still in progress, watch this space.

**Comment by AlexHarker** [comment]
I've now set it so that it complains if you send too many parameters to a window that does take parameters, because that suggests that you don't know what you are doing and thus the user should be alerted, but in the case where the window has no parameters then parameters are just ignored, as I agree that this is too stringent and likely to annoy.
