### ISSUE TITLE
fl.kernelsmooth~ dynamic smoothing

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#72]
Can you change the smoothing amounts (I assume they are up/down or something?) dynamically? The info string says nothing about /smooth being an instantiation amount so should there be a parameter input?

**Comment by AlexHarker** [comment]
This object has not yet been reviewed. If I didn't make a parameter input yet though that seems like an undesirable state of affairs.

**Comment by AlexHarker** [comment]
Fixed on object-review
