### ISSUE TITLE
method __fl.resolve_context called on invalid object

### ISSUE THREAD

**Issue by rconstanzo** [AlexHarker/FrameLib#75]
So testing with the latest version and although I get no crashes, I still get these exact errors.
On trying to freeze the M4L device I get:
`Unable to add unsynced.fl.interval~!`
`freeze complete`

And then I get yellow text for this:
`method __fl.resolve_context called on invalid object`

And when opening the device itself in a Max patch, still get:
`Graph Updated - realtime 1`

This is on OSX 10.14.6 / Max 8.1.8

(I initially commented in the old issue #52, but didn't know if that would go into the void since it's been closed for a while now)

**Comment by rconstanzo** [comment]
So it looks like my Max project was pointing to older versions of some of the externals. I manually removed those and reconsolidated.

So now I get a new error (in blue this time):
`zgetfn (__fl.resolve_context): corrupt object`

And I still get the `Graph Updated` message when running the generated `.amxd` file.

**Comment by jamesb93** [comment]
I have just downloaded the new release of FrameLib and run your max patch (thanks for sending it). I can't get the problem to be replicated and I get no errors. To me it seems like you have an old copy of the externals cached somewhere. Perhaps your best bet is to do a good clean out and start again and ensure there aren't any artefacts laying around.

**Comment by rconstanzo** [comment]
Looks like having ever 'unfrozen' the device on my computer created a version of all the old externals, and for whatever reason, Max decided to use those, even if I explicitly told it to bring in the newer ones and (re)consolidated).

**Comment by AlexHarker** [comment]
Ah - yes - the diagnosis above is correct.
