### ISSUE TITLE
Name aliased externals not found in frozen devices when the package is not present

### ISSUE THREAD

**Issue by rconstanzo** [AlexHarker/FrameLib#78]
Not sure if this is a FrameLib or Max/M4L issue, but when creating a Max project, and subsequently a M4L device using consolidation, it appears that a bunch of the basic operators (`fl.==~`, `fl.<=~`, `fl.>=~`, etc..) aren't parsed by the system.

This is from someones bug report about a confetti device that uses FrameLib:
![Screenshot 2021-02-15 at 2 20 34 pm](https://user-images.githubusercontent.com/2747015/107958279-b1499100-6f99-11eb-9507-61dead12492b.png)

I've double-checked that it's collected all the bits, consolidated again etc... and these operators get left out.

In looking at my list, this could perhaps be the alias thing where the code is using the short form (`fl.==~`) but what is packaged with the project is the verbose form (`fl.equals~`).

I can go back and manually change everything, but it seems like the intention is to be able to use either version.

Here's the code that is eventually throwing up the errors:
![Screenshot 2021-02-15 at 2 20 52 pm](https://user-images.githubusercontent.com/2747015/107958549-14d3be80-6f9a-11eb-99ac-1ed14250797d.png)

**Comment by AlexHarker** [comment]
Yes - this looks like an aliasing problem. This might be a general M$L bug - on your computer you have the package so you get the aliases, but in the frozen device (I presume that is what you are using, is that correct?) it looks like the aliases are not respected or known about. It's also possible that there's some extra magic sauce to apply in order to get this to happen. I'll need to investigate with cycling most likely.

**Comment by rconstanzo** [comment]
Yeah, frozen devices. Was working for mine, and @jamesb93's computers, as we obviously have everything installed.

Is it fair to say that if I rename everything 'verbose' it should work alright?

**Comment by AlexHarker** [comment]
Reported this issue to c74 and will adjust the status here depending on their reply. I've checked on my computer and I consider the behaviour to be a bug, but arguably it may be unsupported. At the moment I don't think I can affect this at all, but I'm awaiting confirmation as to whether there's anything I can do at my end, or whether this needs to be fixed at their end (and whether it will be).

**Comment by jamesb93** [comment]
This is an issue we suffer with flucoma.

@weefuzzy knows the way to navigate this but it's not pretty.

**Comment by AlexHarker** [comment]
Unfortunately that is a workaround and not a fix (a better workaround for framelib is to use non-aliased names, which is not an option in FluCoMa)

**Comment by AlexHarker** [comment]
OK. So I'm going to close up here, but for @rconstanzo and anyone who would like to be able to do this without using full names, here is the workaround.

For each external that you need to alias you need to add a line to the project open actions before freezing (available from the project browser).

Those lines can be copied from fl-objectmappings.txt, but importantly you will need a semicolon before each line.

So in fl-objectmappings.txt for *~ there is:

```max objectfile fl.*~ fl.times~;```

but in your project open actions you need

```;max objectfile fl.*~ fl.times~;```

It's a bit of a shame you can't just copy the whole thing in, but it's not too painful. I've made a suggestion to cycling 74 that this sort of thing should be automated, but I'm not sure if or when that might happen.
